### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by rickerd**
Added curlies, they exist for a reason.
Removed $this->batch array because we set them as a property

### CODE REVIEW

**Comment by rickerd** [comment]
Test the thing out, maby i made a BooBoo because there are no UnitTest for it.
And keep up the good work

**Comment by richard-fizz** [comment]
Will accept the merge request if:

  - Setters and getters are re-introduced; these were added on purpose for extendability reasons.
  - All code is indented consistently with either tabs or spaces

Also not sure how I feel about removing the line that clears all batches after committing the import; maybe add a method clear() that does this, so it can be done manually.

Unit Tests will be introduced soon. Haven't gotten round to it yet unfortunately.

**Comment by rickerd** [comment]
Sorry im not going to put in getters and setters or the other stuff you said.
PHPStorm made the tabs to spaces, i think thats a good thing

And the line that removed all the batches was done by accident.
I was just going trough the code and refactored by SOLID refactoring + code calisthenics

It works so it was only to show or improve readability

**Comment by richard-fizz** [comment]
Fair enough. I will adapt some improvements from this fork to the master repository :)
Of course, either spaces or tabs would be acceptable, but having both ways of indenting scattered around the code is a little bit messy, hence my request.
Thanks for contributing!

**Comment by rickerd** [comment]
I defo understand.

Thanks the contribute :)

---

Met vriendelijke groet,
Rick de Graaff

Verstuurd vanaf mijn iPhone 6

**Pull request closed without merging**
